version: '2'

services:
  web:
    image: php-basic-nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html/
    networks:
      - code-network
  php:
    image: php-basic-php-fpm
    volumes:
      - .:/var/www/html/
    networks:
      - code-network

networks:
  code-network:
    driver: bridge